#!/usr/bin/env bash
set -euo pipefail

DOMAIN="${1:-harrisoncramer.me}"

for tool in aws jq; do
  command -v "$tool" >/dev/null || { echo "missing: $tool" >&2; exit 1; }
done

ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
echo "account: $ACCOUNT" >&2
echo "domain:  $DOMAIN" >&2

ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$DOMAIN" \
  --query "HostedZones[?Name=='${DOMAIN}.'].Id | [0]" --output text | sed 's#/hostedzone/##')

DIST_ID=$(aws cloudfront list-distributions \
  --query "DistributionList.Items[?contains(Aliases.Items, '${DOMAIN}')].Id | [0]" --output text)

CERT_ARN=$(aws acm list-certificates --region us-east-1 \
  --query "CertificateSummaryList[?DomainName=='${DOMAIN}'].CertificateArn | [0]" --output text)

for var in ZONE_ID DIST_ID CERT_ARN; do
  value="${!var}"
  if [ -z "$value" ] || [ "$value" = "None" ]; then
    echo "could not resolve $var for $DOMAIN" >&2
    exit 1
  fi
done

echo "zone:    $ZONE_ID" >&2
echo "dist:    $DIST_ID" >&2
echo "cert:    $CERT_ARN" >&2
echo >&2

emit_bucket_imports() {
  local label="$1" bucket="$2"
  for kind in \
    "aws_s3_bucket" \
    "aws_s3_bucket_ownership_controls" \
    "aws_s3_bucket_public_access_block" \
    "aws_s3_bucket_acl" \
    "aws_s3_bucket_policy"; do
    printf 'import {\n  to = %s.%s\n  id = "%s"\n}\n\n' "$kind" "$label" "$bucket"
  done
}

emit_validation_import() {
  local key="$1"
  local record
  record=$(aws acm describe-certificate --region us-east-1 --certificate-arn "$CERT_ARN" \
    --output json | jq -r --arg d "$key" \
    '.Certificate.DomainValidationOptions[] | select(.DomainName == $d) | .ResourceRecord.Name // empty')
  if [ -z "$record" ]; then
    printf '# no validation record published for %s, import it by hand once ACM shows one\n\n' "$key"
    return
  fi
  record="${record%.}"
  printf 'import {\n  to = aws_route53_record.main["%s"]\n  id = "%s_%s_CNAME"\n}\n\n' \
    "$key" "$ZONE_ID" "$record"
}

cat <<EOF
# Generated by discover.sh against account $ACCOUNT on $(date +%Y-%m-%d).
# Delete this file once the imports have been applied and the state is populated.
#
# Any resource that was never explicitly configured in AWS will fail to import,
# because there is nothing on the account to attach to. When that happens, delete
# the failing import block and the matching resource block together rather than
# letting terraform create it.

EOF

emit_bucket_imports "site" "$DOMAIN"
emit_bucket_imports "assets" "${DOMAIN}.assets"

printf 'import {\n  to = aws_s3_bucket_website_configuration.site\n  id = "%s"\n}\n\n' "$DOMAIN"
printf 'import {\n  to = aws_s3_bucket_versioning.site\n  id = "%s"\n}\n\n' "$DOMAIN"
printf 'import {\n  to = aws_cloudfront_distribution.s3_distribution\n  id = "%s"\n}\n\n' "$DIST_ID"
printf 'import {\n  to = aws_acm_certificate.cert\n  id = "%s"\n}\n\n' "$CERT_ARN"

for rec in "a_record:${DOMAIN}:A" "a_record_www:www.${DOMAIN}:A" \
           "aaaa_record:${DOMAIN}:AAAA" "aaaa_record_www:www.${DOMAIN}:AAAA"; do
  IFS=: read -r label name type <<<"$rec"
  printf 'import {\n  to = aws_route53_record.%s\n  id = "%s_%s_%s"\n}\n\n' \
    "$label" "$ZONE_ID" "$name" "$type"
done

emit_validation_import "$DOMAIN"
emit_validation_import "*.${DOMAIN}"
