name: Deploy the site to AWS
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build production
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production site
        run: npm run build
      - name: Send assets to S3
        uses: reggionick/s3-deploy@v3
        with:
          folder: public
          bucket: ${{ secrets.AWS_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
