name: Deploy the site to AWS
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Add Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build production site
        run: npm run build
      - name: Send hashed assets to S3
        run: |
          aws s3 sync dist/ "s3://$BUCKET/" --delete \
            --exclude "*" --include "_astro/*" \
            --cache-control "public,max-age=31536000,immutable"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      - name: Send the rest of the site to S3
        run: |
          aws s3 sync dist/ "s3://$BUCKET/" --delete \
            --exclude "_astro/*" \
            --cache-control "public,max-age=300,must-revalidate"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      - name: Send the Pagefind WebAssembly to S3
        run: |
          aws s3 cp dist/pagefind/ "s3://$BUCKET/pagefind/" \
            --recursive --exclude "*" --include "*.pagefind" \
            --content-type "application/wasm" \
            --cache-control "public,max-age=300,must-revalidate"
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_BUCKET_REGION }}
          BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      - name: Invalidate the cloudfront distribution
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"
        env:
          AWS_DEFAULT_REGION: us-east-1
      - name: Notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
